"""Prove the minimal Gate-17 FFmpeg helper on the canonical startup derivative path.

The synthetic input is generated by the already-pinned broad BtbN LGPL
candidate only as an ephemeral CI fixture. The minimal helper itself must then
perform the production-shaped MOV/H.264/AAC input -> recovered nearest-neighbor
scale -> h264_mf/AAC -> MP4 path and decode-verify the derivative.

This is still not original-TGQ or human-visible Windows acceptance evidence.
"""
from __future__ import annotations

import argparse
from hashlib import sha256
import json
from pathlib import Path
import subprocess
import tempfile
import zipfile
from typing import Mapping

from gate17_ffmpeg_lgpl_candidate import validate_archive_identity
from gate17_ffmpeg_minimal_source_contract import load_contract
from startup_fmv_presentation import ORIGINAL_STARTUP_FMV_PRESENTATION


class MinimalFfmpegRoundtripError(RuntimeError):
    pass


SYNTHETIC_WIDTH = 320
SYNTHETIC_HEIGHT = 480
SYNTHETIC_FRAME_RATE = 25
SYNTHETIC_FRAME_COUNT = 25
SYNTHETIC_AUDIO_RATE = 22050
SYNTHETIC_AUDIO_CHANNELS = 2


def _sha256_file(path: Path) -> str:
    digest = sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _require_file(path: str | Path, label: str) -> Path:
    target = Path(path).resolve()
    if not target.is_file() or target.stat().st_size <= 0:
        raise MinimalFfmpegRoundtripError(f"{label} is missing or empty: {target}")
    return target


def _load_json(path: str | Path, label: str) -> dict:
    target = _require_file(path, label)
    try:
        payload = json.loads(target.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise MinimalFfmpegRoundtripError(f"{label} is not valid JSON") from exc
    if not isinstance(payload, dict):
        raise MinimalFfmpegRoundtripError(f"{label} root must be an object")
    return payload


def _run(command: tuple[str, ...], *, label: str) -> str:
    try:
        result = subprocess.run(
            command,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            check=False,
        )
    except OSError as exc:
        raise MinimalFfmpegRoundtripError(f"{label} could not start: {exc}") from exc
    if result.returncode != 0:
        raise MinimalFfmpegRoundtripError(
            f"{label} failed with exit code {result.returncode}: "
            f"{(result.stdout or '')[-3000:]}"
        )
    return result.stdout or ""


def build_fixture_command(ffmpeg: Path, output: Path) -> tuple[str, ...]:
    return (
        str(ffmpeg),
        "-hide_banner",
        "-loglevel",
        "error",
        "-nostdin",
        "-f",
        "lavfi",
        "-i",
        f"color=c=black:s={SYNTHETIC_WIDTH}x{SYNTHETIC_HEIGHT}:"
        f"r={SYNTHETIC_FRAME_RATE}:d=1",
        "-f",
        "lavfi",
        "-i",
        f"anullsrc=r={SYNTHETIC_AUDIO_RATE}:cl=stereo:d=1",
        "-map",
        "0:v:0",
        "-map",
        "1:a:0",
        "-c:v",
        "h264_mf",
        "-pix_fmt",
        "yuv420p",
        "-fps_mode",
        "passthrough",
        "-c:a",
        "aac",
        "-ar",
        str(SYNTHETIC_AUDIO_RATE),
        "-ac",
        str(SYNTHETIC_AUDIO_CHANNELS),
        "-movflags",
        "+faststart",
        "-shortest",
        "-y",
        str(output),
    )


def build_minimal_conversion_command(
    ffmpeg: Path,
    source: Path,
    output: Path,
) -> tuple[str, ...]:
    return (
        str(ffmpeg),
        "-hide_banner",
        "-loglevel",
        "error",
        "-nostdin",
        "-n",
        "-i",
        str(source),
        "-map",
        "0:v:0",
        "-map",
        "0:a:0",
        "-vf",
        ORIGINAL_STARTUP_FMV_PRESENTATION.ffmpeg_filter,
        "-c:v",
        "h264_mf",
        "-pix_fmt",
        "yuv420p",
        "-fps_mode",
        "passthrough",
        "-c:a",
        "aac",
        "-ar",
        str(SYNTHETIC_AUDIO_RATE),
        "-ac",
        str(SYNTHETIC_AUDIO_CHANNELS),
        "-movflags",
        "+faststart",
        str(output),
    )


def build_probe_command(ffprobe: Path, path: Path) -> tuple[str, ...]:
    return (
        str(ffprobe),
        "-v",
        "error",
        "-count_frames",
        "-show_streams",
        "-show_format",
        "-of",
        "json",
        str(path),
    )


def build_video_decode_command(ffmpeg: Path, path: Path) -> tuple[str, ...]:
    return (
        str(ffmpeg),
        "-hide_banner",
        "-loglevel",
        "error",
        "-nostdin",
        "-i",
        str(path),
        "-map",
        "0:v:0",
        "-an",
        "-f",
        "null",
        "-",
        "-progress",
        "pipe:1",
        "-nostats",
    )


def build_audio_decode_command(ffmpeg: Path, path: Path) -> tuple[str, ...]:
    return (
        str(ffmpeg),
        "-hide_banner",
        "-loglevel",
        "error",
        "-nostdin",
        "-i",
        str(path),
        "-map",
        "0:a:0",
        "-vn",
        "-f",
        "null",
        "-",
    )


def _int(value: object, label: str) -> int:
    try:
        return int(value)
    except (TypeError, ValueError) as exc:
        raise MinimalFfmpegRoundtripError(f"{label} is missing or invalid") from exc


def _frame_rate(stream: Mapping[str, object], label: str) -> str:
    raw = stream.get("avg_frame_rate") or stream.get("r_frame_rate")
    if raw != f"{SYNTHETIC_FRAME_RATE}/1":
        raise MinimalFfmpegRoundtripError(
            f"{label} frame rate differs from {SYNTHETIC_FRAME_RATE}/1"
        )
    return str(raw)


def validate_media_probe(
    text: str,
    *,
    expected_width: int,
    expected_height: int,
    label: str,
) -> dict:
    try:
        payload = json.loads(text)
    except json.JSONDecodeError as exc:
        raise MinimalFfmpegRoundtripError(f"{label} probe is not valid JSON") from exc
    if not isinstance(payload, dict):
        raise MinimalFfmpegRoundtripError(f"{label} probe root must be an object")
    streams = payload.get("streams")
    if not isinstance(streams, list):
        raise MinimalFfmpegRoundtripError(f"{label} probe streams are missing")
    videos = [item for item in streams if isinstance(item, Mapping) and item.get("codec_type") == "video"]
    audios = [item for item in streams if isinstance(item, Mapping) and item.get("codec_type") == "audio"]
    if len(streams) != 2 or len(videos) != 1 or len(audios) != 1:
        raise MinimalFfmpegRoundtripError(
            f"{label} must contain exactly one video and one audio stream"
        )
    video = videos[0]
    audio = audios[0]
    if (
        video.get("codec_name") != "h264"
        or video.get("pix_fmt") != "yuv420p"
        or _int(video.get("width"), f"{label} width") != expected_width
        or _int(video.get("height"), f"{label} height") != expected_height
    ):
        raise MinimalFfmpegRoundtripError(f"{label} video shape differs from contract")
    rate = _frame_rate(video, label)
    frames = _int(
        video.get("nb_read_frames") if video.get("nb_read_frames") not in (None, "N/A") else video.get("nb_frames"),
        f"{label} video frame count",
    )
    if frames != SYNTHETIC_FRAME_COUNT:
        raise MinimalFfmpegRoundtripError(
            f"{label} video frame count differs from {SYNTHETIC_FRAME_COUNT}"
        )
    if (
        audio.get("codec_name") != "aac"
        or _int(audio.get("sample_rate"), f"{label} audio sample rate") != SYNTHETIC_AUDIO_RATE
        or _int(audio.get("channels"), f"{label} audio channels") != SYNTHETIC_AUDIO_CHANNELS
    ):
        raise MinimalFfmpegRoundtripError(f"{label} audio shape differs from contract")
    format_obj = payload.get("format")
    if not isinstance(format_obj, Mapping):
        raise MinimalFfmpegRoundtripError(f"{label} container metadata is missing")
    names = {
        item.strip().lower()
        for item in str(format_obj.get("format_name", "")).split(",")
        if item.strip()
    }
    if "mp4" not in names:
        raise MinimalFfmpegRoundtripError(f"{label} container is not MP4")
    return {
        "video_codec": "h264",
        "pixel_format": "yuv420p",
        "width": expected_width,
        "height": expected_height,
        "frame_rate": rate,
        "video_frames": frames,
        "audio_codec": "aac",
        "audio_sample_rate": SYNTHETIC_AUDIO_RATE,
        "audio_channels": SYNTHETIC_AUDIO_CHANNELS,
        "container": "mp4",
    }


def validate_decode_progress(text: str) -> dict:
    values: dict[str, str] = {}
    for raw in text.splitlines():
        if "=" in raw:
            key, value = raw.split("=", 1)
            values[key.strip()] = value.strip()
    if values.get("progress") != "end":
        raise MinimalFfmpegRoundtripError("minimal video decode did not reach progress=end")
    if _int(values.get("frame"), "minimal video decode frame count") != SYNTHETIC_FRAME_COUNT:
        raise MinimalFfmpegRoundtripError(
            f"minimal video decode frame count differs from {SYNTHETIC_FRAME_COUNT}"
        )
    return {
        "video_decode_verified": True,
        "decoded_video_frames": SYNTHETIC_FRAME_COUNT,
    }


def validate_build_proof(payload: Mapping[str, object], ffmpeg: Path, ffprobe: Path) -> dict:
    if (
        payload.get("schema_version") != 1
        or payload.get("audit_kind") != "gate17_minimal_ffmpeg_build"
        or payload.get("passed") is not True
        or payload.get("build_verified") is not True
        or payload.get("synthetic_roundtrip_verified") is not False
        or payload.get("production_migration_ready") is not False
        or payload.get("legal_compliance_claimed") is not False
    ):
        raise MinimalFfmpegRoundtripError("minimal build proof is not a valid pre-roundtrip receipt")
    ffmpeg_sha = _sha256_file(ffmpeg)
    ffprobe_sha = _sha256_file(ffprobe)
    if payload.get("ffmpeg_sha256") != ffmpeg_sha:
        raise MinimalFfmpegRoundtripError("minimal ffmpeg.exe differs from build proof")
    if payload.get("ffprobe_sha256") != ffprobe_sha:
        raise MinimalFfmpegRoundtripError("minimal ffprobe.exe differs from build proof")
    return {
        "build_proof_ffmpeg_sha256": ffmpeg_sha,
        "build_proof_ffprobe_sha256": ffprobe_sha,
    }


def audit_minimal_roundtrip(
    *,
    repo_root: str | Path,
    ffmpeg_exe: str | Path,
    ffprobe_exe: str | Path,
    build_proof: str | Path,
    fixture_archive: str | Path,
) -> dict:
    ffmpeg = _require_file(ffmpeg_exe, "minimal ffmpeg.exe")
    ffprobe = _require_file(ffprobe_exe, "minimal ffprobe.exe")
    proof_path = _require_file(build_proof, "minimal build proof")
    proof = _load_json(proof_path, "minimal build proof")
    proof_identity = validate_build_proof(proof, ffmpeg, ffprobe)

    contract, _ = load_contract(repo_root)
    broad = contract["verified_broad_candidate"]
    minimal = contract["minimal_helper_target"]
    if minimal["required_internal_video_conversion"]["expression"] != ORIGINAL_STARTUP_FMV_PRESENTATION.ffmpeg_filter:
        raise MinimalFfmpegRoundtripError("canonical startup video-filter contract drifted")

    fixture_identity = validate_archive_identity(fixture_archive)
    archive = Path(fixture_archive).resolve()
    with tempfile.TemporaryDirectory(prefix="fm2001-minimal-roundtrip-") as temp:
        work = Path(temp)
        fixture_ffmpeg = work / "fixture-ffmpeg.exe"
        with zipfile.ZipFile(archive) as zf:
            fixture_ffmpeg.write_bytes(zf.read(fixture_identity["ffmpeg_member"]))
        fixture_hash = _sha256_file(fixture_ffmpeg)
        if fixture_hash != broad["ffmpeg_sha256"]:
            raise MinimalFfmpegRoundtripError(
                "fixture generator executable differs from pinned broad candidate"
            )

        source = work / "synthetic-startup-source.mp4"
        _run(build_fixture_command(fixture_ffmpeg, source), label="synthetic fixture generation")
        if not source.is_file() or source.stat().st_size <= 0:
            raise MinimalFfmpegRoundtripError("synthetic fixture generation produced no MP4")
        source_probe = validate_media_probe(
            _run(build_probe_command(ffprobe, source), label="synthetic input probe"),
            expected_width=SYNTHETIC_WIDTH,
            expected_height=SYNTHETIC_HEIGHT,
            label="synthetic input",
        )

        output = work / "minimal-startup-derivative.mp4"
        _run(
            build_minimal_conversion_command(ffmpeg, source, output),
            label="minimal canonical startup conversion",
        )
        if not output.is_file() or output.stat().st_size <= 0:
            raise MinimalFfmpegRoundtripError("minimal helper produced no derivative MP4")
        output_probe = validate_media_probe(
            _run(build_probe_command(ffprobe, output), label="minimal output probe"),
            expected_width=ORIGINAL_STARTUP_FMV_PRESENTATION.movie_width,
            expected_height=ORIGINAL_STARTUP_FMV_PRESENTATION.movie_height,
            label="minimal output",
        )
        decode = validate_decode_progress(
            _run(
                build_video_decode_command(ffmpeg, output),
                label="minimal video decode verification",
            )
        )
        _run(
            build_audio_decode_command(ffmpeg, output),
            label="minimal audio decode verification",
        )

        source_sha = _sha256_file(source)
        source_size = source.stat().st_size
        output_sha = _sha256_file(output)
        output_size = output.stat().st_size

    return {
        "schema_version": 1,
        "audit_kind": "gate17_minimal_ffmpeg_synthetic_roundtrip",
        "passed": True,
        **proof_identity,
        "build_proof_sha256": _sha256_file(proof_path),
        "fixture_archive_sha256": fixture_identity["archive_sha256"],
        "fixture_ffmpeg_sha256": broad["ffmpeg_sha256"],
        "fixture_is_ephemeral_test_generator_only": True,
        "synthetic_input": {
            **source_probe,
            "sha256": source_sha,
            "size_bytes": source_size,
        },
        "minimal_output": {
            **output_probe,
            **decode,
            "audio_decode_verified": True,
            "sha256": output_sha,
            "size_bytes": output_size,
        },
        "canonical_video_filter": ORIGINAL_STARTUP_FMV_PRESENTATION.ffmpeg_filter,
        "canonical_video_encoder": "h264_mf",
        "canonical_audio_encoder": "aac",
        "build_verified": True,
        "synthetic_roundtrip_verified": True,
        "exact_original_tgq_verified": False,
        "external_windows11_playback_verified": False,
        "source_material_complete": False,
        "production_migration_ready": False,
        "legal_compliance_claimed": False,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parent.parent)
    parser.add_argument("--ffmpeg", type=Path, required=True)
    parser.add_argument("--ffprobe", type=Path, required=True)
    parser.add_argument("--build-proof", type=Path, required=True)
    parser.add_argument("--fixture-archive", type=Path, required=True)
    parser.add_argument("--output-receipt", type=Path, required=True)
    args = parser.parse_args()

    result = audit_minimal_roundtrip(
        repo_root=args.repo_root,
        ffmpeg_exe=args.ffmpeg,
        ffprobe_exe=args.ffprobe,
        build_proof=args.build_proof,
        fixture_archive=args.fixture_archive,
    )
    args.output_receipt.parent.mkdir(parents=True, exist_ok=True)
    args.output_receipt.write_text(
        json.dumps(result, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
