"""Minimum recovered support-staff state needed by Gate-11 training.

This module deliberately stops at the source-backed boundary. It reproduces the
fixed fresh-user staff generator and the training-quality lookup semantics, but
it does not attach those draws to GameState startup until the exact shared CRT
state after the secondary schedule/support-pool startup work is reconstructed.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, Protocol


class BoundedRng(Protocol):
    def randbelow(self, bound: int) -> int: ...


INITIAL_SUPPORT_STAFF_TYPES = (1, 2, 3, 4, 5, 13)
ASSISTANT_MANAGER_TYPE = 2
YOUTH_TEAM_COACH_TYPE = 3


@dataclass(frozen=True)
class SupportStaffState:
    """Training-relevant subset of the original 0x218-byte CSupportStaff."""

    staff_type: int
    age_like: int
    rating: int
    status: int = 1

    @property
    def effective_training_rating(self) -> int:
        """Original virtual +0x40 behavior used by active training."""
        if int(self.status) == 2:
            return 1
        return int(self.rating)


def initial_staff_rating_base(competition_context: int) -> int:
    """Map the 0x4FA520 context to the base used by 0x4C9D40.

    Context cases 0/1/2 use bases 4/3/2. Case 3 and every later/default
    context use base 1. Premier League competition 0 is in the default family.
    """

    context = int(competition_context)
    if context == 0:
        return 4
    if context == 1:
        return 3
    if context == 2:
        return 2
    return 1


def generate_fixed_initial_staff(
    rng: BoundedRng,
    staff_type: int,
    competition_context: int,
) -> SupportStaffState:
    """Reproduce one 0x4C9D40(type) fixed fresh-user staff creation.

    Exact bounded draws, in order:
      RNG(25)+25 -> age-like field
      RNG(2)+tier_base -> rating

    Types 1..5 take the default-success compatibility path and therefore enter
    fresh user state with status 1. The only Gate-11 training staff are types
    2 and 3, both inside that range.
    """

    staff_type = int(staff_type)
    if staff_type <= 0:
        raise ValueError("staff_type must be positive")
    age_like = int(rng.randbelow(25)) + 25
    rating = int(rng.randbelow(2)) + initial_staff_rating_base(
        competition_context
    )
    return SupportStaffState(
        staff_type=staff_type,
        age_like=age_like,
        rating=rating,
        status=1,
    )


def generate_fresh_user_support_staff(
    rng: BoundedRng,
    competition_context: int,
) -> tuple[SupportStaffState, ...]:
    """Create the six fixed staff generated by 0x4D1760 in original order."""

    return tuple(
        generate_fixed_initial_staff(rng, staff_type, competition_context)
        for staff_type in INITIAL_SUPPORT_STAFF_TYPES
    )


def training_quality_multiplier(
    staff: Iterable[SupportStaffState],
    *,
    has_training_centre: bool = False,
) -> float:
    """Return the exact source-backed quality multiplier used by 0x4EACE0.

    Youth Team Coach (type 3) takes precedence. Its effective 1..5 rating maps
    to 1.25/1.30/1.35/1.40/1.45. If no youth coach exists but an Assistant
    Manager (type 2) does, the fallback is 1.25. Training Centre feature ID 5
    then adds exactly +0.25.
    """

    staff = tuple(staff)
    youth = next(
        (item for item in staff if int(item.staff_type) == YOUTH_TEAM_COACH_TYPE),
        None,
    )
    if youth is not None:
        rating = max(1, min(5, int(youth.effective_training_rating)))
        quality = 1.20 + 0.05 * rating
    else:
        assistant = next(
            (
                item
                for item in staff
                if int(item.staff_type) == ASSISTANT_MANAGER_TYPE
            ),
            None,
        )
        quality = 1.25 if assistant is not None else 1.0

    if has_training_centre:
        quality += 0.25
    return quality
